<?php

/**
 * @file
 * RTI Deployment module. File intentionally left blank.
 */
function get_menu_path($link_title) {
  if ($link_title) {
    switch ($link_title) {
      case 'Featured Items':
        return 'resources/featured';

      case 'For Parents':
        return 'resources/parents';

      case 'Events':
        return 'events';

      case 'About RTI':
        return 'about-rti';

      case 'Contact Us':
        return 'contact-us';

      default:
        return '<front>';
    }
  }
}
