<?php
/**
 * @file
 * presentation.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function presentation_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function presentation_node_info() {
  $items = array(
    'presentation' => array(
      'name' => t('Presentation'),
      'base' => 'node_content',
      'description' => t('Describe the Presentation. Use the summary link above the this field for the short description that goes on the resource listings pages. This text will be in the longer, full-length Presentation item page.
'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
